import { Quote } from "./types";

// ─── DR JEKYLL AND MR HYDE — 6 Quotes ───

export const JEKYLL_HYDE_QUOTES: Quote[] = [
  {
    id: 1,
    textSlug: "jekyll-hyde",
    quote: "Mr Hyde was pale and dwarfish, he gave an impression of deformity without any nameable malformation",
    who: "Narrator (Enfield)",
    act: "Chapter 1: Story of the Door",
    themes: ["Duality", "Appearance vs Reality", "Victorian Repression", "Science & Morality"],
    keyQuote: {
      text: '"Mr Hyde was pale and dwarfish, he gave an impression of deformity without any nameable malformation"',
      highlight: "deformity",
      note: "The first physical description of Hyde captures the novella's central paradox: his evil is felt instinctively but cannot be articulated, suggesting that moral corruption defies rational description.",
    },
    technique1: {
      title: "SEMANTIC NEGATION / THE INEFFABLE",
      analysis:
        "The phrase 'without any **nameable** malformation' uses **semantic negation** (defining something by what it is NOT) — Hyde's deformity exists but cannot be described. This **ineffability** (the quality of being impossible to express in words) is Stevenson's most unsettling technique: the characters feel Hyde's evil viscerally but cannot explain it rationally. Language — the tool of civilised reason — fails when confronted with primal evil.",
      secondPoint:
        "The word '**impression**' is carefully chosen: it suggests something received passively, like a mark pressed into soft material. Hyde does not announce his evil; he imprints it on observers. This **passive construction** positions Hyde's effect as involuntary and physical, bypassing rational analysis entirely — you feel his wrongness before you can think about it.",
      keyWords: [
        { word: "Semantic negation", def: "Defining something by what it is not; describing through absence" },
        { word: "Ineffable", def: "Too great, extreme, or powerful to be expressed in words" },
        { word: "Visceral", def: "Relating to deep, instinctive feelings rather than rational thought" },
      ],
    },
    rad: {
      label: "STAGNATE",
      analysis:
        "Hyde does not develop — he is a **static** embodiment of evil from his first appearance. His **stagnation** mirrors his nature: as the expression of Jekyll's repressed desires, he is not a character who grows but a force that has been **unleashed** (released from confinement). Hyde's unchanging nature contrasts with Jekyll's deteriorating control, making Hyde's stagnation itself a form of threat — he is always the same, always terrible.",
      keyWords: [
        { word: "Static embodiment", def: "An unchanging physical representation of an abstract concept" },
        { word: "Unleashed", def: "Released from restraint; set free" },
      ],
    },
    technique2: {
      title: "PHYSIOGNOMY & VICTORIAN PSEUDO-SCIENCE",
      analysis:
        "Stevenson invokes the Victorian pseudo-science of **physiognomy** (the belief that physical appearance reveals moral character) — but then **subverts** (undermines) it. Hyde's evil should be readable on his face, but the observers cannot describe what they see. This failure exposes the inadequacy of physiognomy: morality cannot be reduced to physical measurement. Evil is not a visible attribute but an **atmospheric** (relating to mood or feeling) presence.",
      secondPoint:
        "The adjective '**dwarfish**' connects Hyde to Victorian anxieties about **degeneration** (the theory that civilisation could reverse, producing more primitive beings). Hyde is physically smaller and less evolved than Jekyll, suggesting that the 'lower' self is a regression to an earlier, more **atavistic** (reverting to ancestral traits) stage of human development.",
      keyWords: [
        { word: "Physiognomy", def: "The pseudo-scientific belief that physical features reveal moral character" },
        { word: "Degeneration", def: "The Victorian theory that civilisation could reverse, producing primitive beings" },
        { word: "Atavistic", def: "Reverting to ancestral or primitive traits; a throwback to an earlier stage of development" },
      ],
    },
    context: {
      points: [
        {
          label: "VICTORIAN RESPECTABILITY",
          text: "Victorian society demanded a rigid public performance of **respectability** (adherence to the moral standards expected by society). Gentlemen were expected to be rational, self-controlled, and morally upright. Hyde's existence exposes the gap between this public performance and the private desires it conceals — the respectable surface is a **veneer** (a thin decorative covering hiding inferior material) over darker impulses.",
        },
        {
          label: "DARWIN & EVOLUTION ANXIETY",
          text: "Published in 1886, the novella reflects anxieties generated by Darwin's **Origin of Species** (1859). If humans evolved from animals, then the 'beast' within was not metaphorical but biological. Hyde represents the **evolutionary regression** Victorians feared — the possibility that civilisation's progress could be reversed, revealing the animal within the gentleman.",
        },
      ],
      keyWords: [
        { word: "Respectability", def: "The quality of being socially acceptable and morally upright" },
        { word: "Veneer", def: "A surface appearance that conceals the true nature of something" },
        { word: "Evolutionary regression", def: "The reversal of evolutionary progress; returning to a more primitive state" },
      ],
    },
    wow: {
      title: "THE UNCANNY (Freud)",
      analysis:
        "Sigmund Freud defined the **Uncanny** (*das Unheimliche*) as the sensation of encountering something simultaneously familiar and strange — something that should have remained hidden but has come to light. Hyde is profoundly uncanny: he is Jekyll — familiar — yet distorted into something unrecognisable and terrifying. The observers' inability to describe his deformity is itself uncanny: they recognise evil but cannot name it, because naming would require acknowledging that it exists within respectable society, within themselves. Stevenson's genius is locating horror not in the exotic or supernatural but in the **domestic** and familiar — the respectable doctor's drawing room, the gentleman's private quarters. The real terror of Hyde is not that he is alien but that he is intimately **proximate** (close) — he is us, unmasked.",
      keyWords: [
        { word: "The Uncanny", def: "Freud's concept of the disturbing feeling caused by something both familiar and strange" },
        { word: "Proximate", def: "Very near; close in relationship or resemblance" },
        { word: "Domestic horror", def: "Terror located within the familiar spaces of home and everyday life" },
      ],
    },
  },
  {
    id: 2,
    textSlug: "jekyll-hyde",
    quote: "Man is not truly one, but truly two",
    who: "Dr Jekyll",
    act: "Chapter 10: Henry Jekyll's Full Statement",
    themes: ["Duality", "Science & Morality", "Victorian Repression", "Identity"],
    keyQuote: {
      text: '"Man is not truly one, but truly two"',
      highlight: "two",
      note: "Jekyll's philosophical declaration — the thesis of the entire novella — asserts that human nature is fundamentally divided, containing both good and evil in unstable coexistence.",
    },
    technique1: {
      title: "ANTITHETICAL PARALLELISM / UNIVERSAL CLAIM",
      analysis:
        "The **antithetical** (contrasting) structure — 'not truly one, but truly two' — uses **parallelism** (matching grammatical structures) to present duality as a balanced, scientific observation. The universal noun '**Man**' (humanity) transforms Jekyll's personal experience into a claim about human nature itself — this is not one doctor's peculiar condition but a **universal truth** about the human species.",
      secondPoint:
        "The repetition of '**truly**' is deeply ironic: Jekyll claims to have discovered truth, but his experiment to separate good from evil fails catastrophically. The word 'truly' carries the weight of scientific certainty, yet the story demonstrates that his 'truth' is dangerously **reductive** (oversimplifying a complex reality) — human nature cannot be neatly divided into two components.",
      keyWords: [
        { word: "Antithetical", def: "Directly opposite or contrasting; arranged in balanced opposition" },
        { word: "Parallelism", def: "Using matching grammatical structures to create balance and emphasis" },
        { word: "Reductive", def: "Oversimplifying something complex; reducing it to fewer elements than it contains" },
      ],
    },
    rad: {
      label: "REGRESS",
      analysis:
        "Jekyll's confession reveals his **regression**: in attempting to purify his good side by separating out the evil, he has instead liberated a force he cannot control. His scientific ambition has produced moral catastrophe — a **regression** from civilised doctor to enabler of murder. The tragedy is that his intention was moral improvement; the result was its opposite.",
      keyWords: [
        { word: "Liberation", def: "Setting free from confinement or control" },
        { word: "Moral catastrophe", def: "A disastrous outcome resulting from ethical failure or miscalculation" },
      ],
    },
    technique2: {
      title: "SCIENTIFIC REGISTER / CLINICAL DETACHMENT",
      analysis:
        "Jekyll's statement uses the register of **scientific observation** — detached, analytical, declarative — to describe what is essentially a moral and spiritual crisis. This **clinical detachment** (emotionally distant, medical tone) reveals Jekyll's fundamental error: he approaches the human soul as if it were a chemical compound that can be separated in a laboratory. Stevenson critiques the Victorian faith in science's ability to solve all problems, including moral ones.",
      secondPoint:
        "The use of 'Man' rather than 'I' performs a crucial **distancing** function: Jekyll presents his personal crisis as universal philosophy, avoiding direct confession. This **deflection** (redirecting attention away from oneself) through generalisation is itself a form of the respectable concealment that the novella criticises — even in his final confession, Jekyll cannot fully own what he has done.",
      keyWords: [
        { word: "Clinical detachment", def: "An emotionally distant, medical tone when discussing disturbing subjects" },
        { word: "Scientific register", def: "The formal, analytical language associated with scientific writing" },
        { word: "Deflection", def: "Redirecting attention away from oneself; avoiding direct personal responsibility" },
      ],
    },
    context: {
      points: [
        {
          label: "VICTORIAN SCIENCE & ETHICS",
          text: "The late 19th century saw rapid scientific advancement — anaesthesia, germ theory, vaccination — fuelling a belief that science could solve any problem. Stevenson questions this **positivist** (believing that only scientific knowledge is valid) confidence: Jekyll's experiment demonstrates that some problems — moral, psychological, spiritual — cannot be solved by chemistry. Science without ethics produces monsters.",
        },
        {
          label: "DUALITY IN VICTORIAN CULTURE",
          text: "Victorian society was structured around **binary oppositions**: respectable/disreputable, public/private, male/female, reason/passion. Jekyll's statement challenges these binaries by suggesting they coexist within every individual. The novella was published during a period of growing **psychological understanding** — anticipating Freud's model of the divided self.",
        },
      ],
      keyWords: [
        { word: "Positivist", def: "A philosophy that only scientific, empirically verifiable knowledge is valid" },
        { word: "Binary oppositions", def: "Paired concepts considered as direct opposites (good/evil, reason/passion)" },
        { word: "Divided self", def: "The concept that human identity contains conflicting, contradictory elements" },
      ],
    },
    wow: {
      title: "THE ID, EGO, AND SUPEREGO (Freud)",
      analysis:
        "Freud's **structural model of the psyche** (published 1923, but anticipated by Stevenson in 1886) divides the mind into three parts: the **Id** (primitive desires), the **Ego** (rational self), and the **Superego** (moral conscience). Jekyll represents the Ego and Superego — the respectable, rational, moral man — while Hyde is the pure **Id**: desire without conscience, impulse without restraint. Jekyll's experiment is an attempt to separate the Superego from the Id, liberating both — but Freud would argue this is impossible, because the three components are structurally interdependent. The Id without the Ego's mediation becomes destructive chaos (Hyde); the Superego without the Id becomes repressive denial (Jekyll's tortured respectability). Stevenson's novella is a case study in what happens when the psyche's necessary balance is artificially disrupted.",
      keyWords: [
        { word: "Id", def: "Freud's term for the primitive, instinctive part of the mind driven by desire" },
        { word: "Ego", def: "The rational, conscious part of the mind that mediates between desire and morality" },
        { word: "Superego", def: "The moral conscience; the part of the mind that enforces social rules and ideals" },
      ],
    },
  },
  {
    id: 3,
    textSlug: "jekyll-hyde",
    quote: "I was slowly losing hold of my original and better self, and becoming slowly incorporated with my second and worse",
    who: "Dr Jekyll",
    act: "Chapter 10: Henry Jekyll's Full Statement",
    themes: ["Duality", "Moral Corruption", "Victorian Repression", "Science & Morality"],
    keyQuote: {
      text: '"I was slowly losing hold of my original and better self, and becoming slowly incorporated with my second and worse"',
      highlight: "slowly",
      note: "Jekyll confesses that the transformations are becoming involuntary — Hyde is no longer a choice but an identity consuming him, revealing the addictive nature of moral transgression.",
    },
    technique1: {
      title: "TEMPORAL ADVERBS / GRADUAL DISSOLUTION",
      analysis:
        "The repeated adverb '**slowly**' emphasises the **gradual** nature of Jekyll's moral dissolution — evil does not arrive suddenly but **incrementally** (bit by bit, in small steps). This challenges the Victorian assumption that moral corruption is a dramatic event (a single 'fall') and instead presents it as a **process** of accumulation, like a disease progressing through stages.",
      secondPoint:
        "The verb '**incorporated**' (literally 'made into one body') is etymologically precise: Hyde is being absorbed into Jekyll's physical form. This **corporeal** (relating to the body) language suggests that moral corruption is not merely spiritual but physical — evil changes what you ARE, not just what you DO. The body becomes the site of moral transformation.",
      keyWords: [
        { word: "Incremental", def: "Happening in small, gradual steps rather than all at once" },
        { word: "Dissolution", def: "The gradual breaking down or disintegration of something" },
        { word: "Corporeal", def: "Relating to the physical body" },
      ],
    },
    rad: {
      label: "REGRESS",
      analysis:
        "Jekyll's **regression** has become involuntary: the transformation no longer requires the potion but happens spontaneously, suggesting that Hyde is not a separate entity but Jekyll's **authentic** (genuine, true) self emerging. The 'original and better self' is being consumed by the 'second and worse,' implying that the veneer of respectability was always thinner than Jekyll believed.",
      keyWords: [
        { word: "Involuntary", def: "Done without conscious choice or control" },
        { word: "Authentic", def: "Genuine; representing one's true nature rather than a performance" },
      ],
    },
    technique2: {
      title: "ANTITHETICAL LEXICAL PAIRS",
      analysis:
        "The **antithetical** (opposing) pairs — 'original'/'second', 'better'/'worse' — create a **binary structure** that mirrors the novella's central duality. But the sentence's meaning undermines this neatness: the boundaries between 'original' and 'second' are **dissolving**. Stevenson uses the form of binary opposition to describe its collapse — the structure of the language contradicts its content, mirroring Jekyll's disintegrating identity.",
      secondPoint:
        "The qualifier '**and better**' reveals Jekyll's self-deception: even in confession, he insists on categorising his respectable self as morally superior. Stevenson invites the reader to question this: was Jekyll's 'original' self truly better, or was his respectability merely the suppression of desires that Hyde now expresses? The novella never resolves this question, leaving moral judgment **suspended** (held in uncertainty).",
      keyWords: [
        { word: "Antithetical lexical pairs", def: "Opposing word choices placed together to create contrast" },
        { word: "Self-deception", def: "The act of misleading oneself about the truth of a situation" },
        { word: "Suspended judgment", def: "Withholding a definitive moral conclusion; maintaining uncertainty" },
      ],
    },
    context: {
      points: [
        {
          label: "ADDICTION & LOSS OF CONTROL",
          text: "Jekyll's description mirrors the language of **addiction**: initial voluntary use becomes compulsive need, until the substance controls the user. Victorian society was grappling with **opium** and **alcohol** addiction in the working and professional classes. Stevenson — who used cocaine medicinally — understood the dynamics of substances that promise liberation but deliver enslavement.",
        },
        {
          label: "THE DOUBLE LIFE",
          text: "Many respectable Victorian gentlemen led **double lives**: maintaining public respectability while secretly visiting brothels, opium dens, or engaging in illegal activities. The West End/East End divide in London physically separated respectability from vice. Jekyll's transformation literalises this cultural phenomenon — the 'double life' becomes a double body.",
        },
      ],
      keyWords: [
        { word: "Addiction", def: "Compulsive dependence on a substance or behaviour despite harmful consequences" },
        { word: "Double life", def: "Living two separate, contradictory existences simultaneously" },
        { word: "Literalise", def: "To make a metaphor physical and real; to embody an abstract concept" },
      ],
    },
    wow: {
      title: "HEGEMONIC MASCULINITY (Connell)",
      analysis:
        "R.W. Connell's theory of **hegemonic masculinity** describes the dominant form of manhood that society enforces — rational, controlled, heterosexual, authoritative. Jekyll embodies hegemonic masculinity perfectly: he is a respected doctor, a bachelor of means, a pillar of the community. But this performance requires the **suppression** of desires that do not fit the model. Hyde represents what hegemonic masculinity excludes — aggression, desire, irrationality — and his emergence suggests that rigid gender performance is inherently **unsustainable**. Stevenson's novella can be read as an argument that the more rigidly a society enforces ideals of masculine respectability, the more violently the repressed elements will eventually erupt.",
      keyWords: [
        { word: "Hegemonic masculinity", def: "The dominant, socially enforced ideal of manhood in a given society" },
        { word: "Suppression", def: "The conscious act of restraining or preventing the expression of desires" },
        { word: "Unsustainable", def: "Unable to be maintained at the current level; destined to collapse" },
      ],
    },
  },
  {
    id: 4,
    textSlug: "jekyll-hyde",
    quote: "If he be Mr Hyde... I shall be Mr Seek",
    who: "Mr Utterson",
    act: "Chapter 2: Search for Mr Hyde",
    themes: ["Duality", "Appearance vs Reality", "Friendship & Loyalty", "Victorian Repression"],
    keyQuote: {
      text: '"If he be Mr Hyde... I shall be Mr Seek"',
      highlight: "Seek",
      note: "Utterson's determined wordplay — transforming Hyde's name into a game of hide-and-seek — reveals the novella's pursuit narrative and the Victorian compulsion to uncover hidden truths.",
    },
    technique1: {
      title: "PUNS / ONOMASTIC WORDPLAY",
      analysis:
        "The **pun** (a play on words exploiting multiple meanings) on 'Hyde/Hide' and 'Seek' creates an **onomastic** (relating to names) system of meaning: Hyde's very name encodes his function — he is the hidden self, the concealed identity. Stevenson makes naming itself a form of characterisation: to be called 'Hyde' is to be defined as that which is hidden, secret, and denied.",
      secondPoint:
        "Utterson's determination to 'seek' positions him as the novella's rational investigator — a figure who believes that truth can be uncovered through **empirical** (based on observation and evidence) inquiry. But the game of hide-and-seek is a children's game, introducing an element of **naivety**: Utterson does not understand that what he seeks is not merely a criminal but a fundamental truth about human nature that will shatter his comfortable worldview.",
      keyWords: [
        { word: "Pun", def: "A play on words that exploits multiple meanings or similar sounds" },
        { word: "Onomastic", def: "Relating to names and their significance" },
        { word: "Empirical", def: "Based on observation and evidence rather than theory" },
      ],
    },
    rad: {
      label: "STAGNATE",
      analysis:
        "Utterson remains morally **static** throughout the novella: he is a good, loyal, rational man from beginning to end. His **stagnation** serves a structural purpose — as the fixed moral centre, he provides a stable perspective from which the reader can observe Jekyll's disintegration. But his inability to imagine the truth also makes his rationality a **limitation**: the most respectable man in the story is the last to understand what is happening.",
      keyWords: [
        { word: "Fixed moral centre", def: "A character who provides a stable ethical perspective throughout the narrative" },
        { word: "Limitation", def: "A restriction or constraint that prevents full understanding or action" },
      ],
    },
    technique2: {
      title: "DETECTIVE NARRATIVE / GENRE SUBVERSION",
      analysis:
        "Stevenson sets up a **detective narrative** (a story structured around the investigation of a mystery) with Utterson as the rational investigator. But the novella **subverts** (undermines) this genre: the mystery's solution — that Jekyll and Hyde are the same person — cannot be reached through rational deduction because it defies rational possibility. The failure of the detective genre mirrors the failure of Victorian **rationalism** (the belief that reason can explain everything) to account for the irrational depths of human nature.",
      secondPoint:
        "The narrative structure itself withholds truth: the final revelation comes through Jekyll's written confession, not through Utterson's investigation. This structural choice suggests that some truths cannot be discovered from the outside — they must be **confessed** from within, because they exist in the hidden interior of the self.",
      keyWords: [
        { word: "Detective narrative", def: "A story structured around the systematic investigation of a mystery" },
        { word: "Genre subversion", def: "Deliberately undermining the conventions and expectations of a literary genre" },
        { word: "Rationalism", def: "The belief that reason and logic can explain all phenomena" },
      ],
    },
    context: {
      points: [
        {
          label: "VICTORIAN INVESTIGATIONS",
          text: "The 1880s saw growing public interest in the hidden underworld of Victorian cities: **investigative journalism** (Henry Mayhew's *London Labour and the London Poor*), police reform, and the emerging science of **criminology** all reflected a desire to make the invisible visible. Utterson embodies this impulse — the respectable professional who investigates what lies beneath the surface.",
        },
        {
          label: "MALE FRIENDSHIP & SILENCE",
          text: "The novella is populated entirely by men whose relationships are characterised by profound **reticence** (restraint in expressing feelings). Utterson's loyalty to Jekyll is deep but unexpressed; the characters never discuss emotions openly. Stevenson shows that Victorian masculine culture's emphasis on **stoicism** (enduring pain without showing emotion) creates the very conditions that allow secrets like Hyde to flourish — what cannot be spoken cannot be confronted.",
        },
      ],
      keyWords: [
        { word: "Investigative journalism", def: "Reporting that involves thorough research to uncover concealed truths" },
        { word: "Reticence", def: "Reluctance to express emotions or reveal personal information" },
        { word: "Stoicism", def: "Enduring hardship without showing emotion; emotional self-restraint" },
      ],
    },
    wow: {
      title: "THE EPISTEMOLOGY OF THE CLOSET (Sedgwick)",
      analysis:
        "Eve Kosofsky Sedgwick's concept of the **Epistemology of the Closet** examines how Victorian culture created a structure of **open secrets** — things that everyone knows but no one acknowledges. The novella operates on this principle: Jekyll's 'secret' is elaborately hidden yet simultaneously suspected by everyone around him. The structure of concealment and investigation mirrors what Sedgwick calls the **closet**: a space of identity that is simultaneously hidden and visible, private and public. Stevenson's narrative — where respectable men desperately avoid naming what they suspect — captures the dynamics of a society that produces secrets through the very ferocity of its demand for transparency. The more aggressively Victorian culture policed respectability, the more elaborate the structures of concealment had to become.",
      keyWords: [
        { word: "Epistemology of the Closet", def: "Sedgwick's theory about the cultural dynamics of secrets, concealment, and identity" },
        { word: "Open secret", def: "Something widely known but not publicly acknowledged" },
        { word: "Policing respectability", def: "The social enforcement of moral standards through surveillance and judgment" },
      ],
    },
  },
  {
    id: 5,
    textSlug: "jekyll-hyde",
    quote: "I felt younger, lighter, happier in body... a solution of the bonds of obligation",
    who: "Dr Jekyll",
    act: "Chapter 10: Henry Jekyll's Full Statement",
    themes: ["Victorian Repression", "Duality", "Moral Corruption", "Science & Morality"],
    keyQuote: {
      text: '"I felt younger, lighter, happier in body... a solution of the bonds of obligation"',
      highlight: "lighter",
      note: "Jekyll's description of his first transformation reveals the seductive pleasure of shedding moral responsibility — becoming Hyde feels like liberation, not damnation.",
    },
    technique1: {
      title: "SEMANTIC FIELD OF LIBERATION",
      analysis:
        "The adjectives '**younger, lighter, happier**' create a **semantic field** (a group of words connected by meaning) of liberation and joy — the opposite of what the reader expects from a transformation into evil. Stevenson makes a deeply uncomfortable argument: shedding morality feels good. The removal of conscience is experienced as **euphoria** (intense happiness), suggesting that Victorian moral codes were experienced as a heavy burden, not a natural state.",
      secondPoint:
        "The phrase 'solution of the bonds of obligation' uses the chemical meaning of '**solution**' (dissolving a solid into liquid) to describe the dissolution of moral responsibility. This conflation of chemical and moral language is deeply **Janus-faced** (looking in two directions): the potion dissolves both the physical boundaries between Jekyll and Hyde AND the moral boundaries between good and evil.",
      keyWords: [
        { word: "Semantic field", def: "A group of words related by meaning, creating a pattern of association" },
        { word: "Euphoria", def: "A feeling of intense happiness and excitement" },
        { word: "Janus-faced", def: "Having two contrasting aspects or interpretations; looking in two directions" },
      ],
    },
    rad: {
      label: "REGRESS",
      analysis:
        "Jekyll's 'liberation' is actually a profound **regression**: he is not becoming more free but less human. The joy he feels is the joy of a man discarding his conscience — exhilarating in the moment but ultimately destructive. Stevenson suggests that moral obligation, while burdensome, is what makes us fully human; its removal does not liberate but **diminishes** (makes smaller, lesser) us.",
      keyWords: [
        { word: "Diminish", def: "To make or become smaller, less, or lower in value or importance" },
        { word: "Exhilarating", def: "Making one feel very happy, animated, or elated" },
      ],
    },
    technique2: {
      title: "UNRELIABLE NARRATOR / SELF-JUSTIFICATION",
      analysis:
        "Jekyll writes his confession retrospectively, knowing the full horror of what Hyde became. Yet his description of the first transformation is suffused with **nostalgia** (a sentimental longing for the past) — he cannot help recalling the pleasure even as he confesses the crime. This makes Jekyll an **unreliable narrator** (a narrator whose account cannot be fully trusted): his confession is simultaneously truthful and self-serving, honest and **evasive** (avoiding full disclosure).",
      secondPoint:
        "The passive constructions — 'I FELT younger' rather than 'I BECAME worse' — maintain Jekyll's distance from moral responsibility. He describes sensations, not choices. This **grammatical evasion** mirrors his psychological evasion: even in his final statement, Jekyll frames himself as the passive experiencer of transformation rather than its active agent.",
      keyWords: [
        { word: "Unreliable narrator", def: "A narrator whose account is potentially biased, incomplete, or self-serving" },
        { word: "Evasive", def: "Tending to avoid commitment or self-disclosure; deliberately vague" },
        { word: "Grammatical evasion", def: "Using passive or indirect constructions to avoid direct responsibility" },
      ],
    },
    context: {
      points: [
        {
          label: "VICTORIAN MORAL BURDEN",
          text: "Victorian gentlemen were expected to be paragons of **self-discipline** — controlling appetites, managing emotions, and presenting a spotless public image. Jekyll's euphoria at becoming Hyde suggests that this moral performance was experienced as **oppressive** (unjustly harsh and authoritarian). Stevenson sympathises with the desire for release while showing its catastrophic consequences.",
        },
        {
          label: "SUBSTANCE USE & ESCAPE",
          text: "The transformation scene mirrors accounts of **intoxication** — the initial euphoria, the sense of freedom, the gradual loss of control. Victorian London had widespread opium use, particularly in professional circles. Stevenson himself wrote the first draft in a cocaine-fuelled three-day writing binge, adding biographical resonance to the theme of chemical transformation.",
        },
      ],
      keyWords: [
        { word: "Self-discipline", def: "The ability to control one's feelings and actions through willpower" },
        { word: "Oppressive", def: "Unjustly harsh, authoritarian, or burdensome" },
        { word: "Intoxication", def: "The state of being under the influence of a substance that alters perception" },
      ],
    },
    wow: {
      title: "THE PLEASURE PRINCIPLE (Freud)",
      analysis:
        "Freud's **Pleasure Principle** states that the Id seeks immediate gratification and the avoidance of pain, while the **Reality Principle** (governed by the Ego) defers pleasure in favour of social functioning. Jekyll's transformation enacts the triumph of the Pleasure Principle: Hyde is pure Id, freed from the Reality Principle's constraints. The 'bonds of obligation' Jekyll sheds are precisely the Reality Principle's demands — social propriety, moral codes, professional responsibility. Stevenson reveals the terrifying implication: beneath every respectable Victorian gentleman, the Pleasure Principle is straining against its bonds. **Civilisation** itself, Freud would later argue in *Civilisation and Its Discontents*, is built on the painful suppression of instinctual desire — and that suppression can never be permanent.",
      keyWords: [
        { word: "Pleasure Principle", def: "Freud's concept that the Id seeks immediate gratification and avoidance of pain" },
        { word: "Reality Principle", def: "The Ego's capacity to defer pleasure in favour of social and practical demands" },
        { word: "Civilisation", def: "Organised human society, built (according to Freud) on the suppression of instinctual desire" },
      ],
    },
  },
  {
    id: 6,
    textSlug: "jekyll-hyde",
    quote: "It was on the moral side, and in my own person, that I learned to recognise the thorough and primitive duality of man",
    who: "Dr Jekyll",
    act: "Chapter 10: Henry Jekyll's Full Statement",
    themes: ["Duality", "Science & Morality", "Victorian Repression", "Identity"],
    keyQuote: {
      text: '"It was on the moral side, and in my own person, that I learned to recognise the thorough and primitive duality of man"',
      highlight: "primitive",
      note: "Jekyll's philosophical conclusion — that duality is 'thorough and primitive' — suggests that the division between good and evil is not exceptional but fundamental to human nature.",
    },
    technique1: {
      title: "LATINATE REGISTER / ACADEMIC AUTHORITY",
      analysis:
        "Jekyll employs a **Latinate** (derived from Latin, used in academic and scientific discourse) register: 'recognise', 'thorough', 'primitive', 'duality'. This elevated vocabulary lends his statement the authority of a **scientific paper** — he frames his murderous experience as a contribution to knowledge. The tension between the formality of his language and the horror of his content creates a deeply unsettling **dissonance** (a clash between things that do not harmonise).",
      secondPoint:
        "The word '**primitive**' (from Latin *primitivus*, 'first of its kind') carries evolutionary connotations: duality is not a modern condition but an **ancient**, fundamental aspect of human nature. This connects to Victorian anxieties about Darwin — if duality is primitive, it predates civilisation and cannot be eliminated by it.",
      keyWords: [
        { word: "Latinate register", def: "Formal, academic vocabulary derived from Latin" },
        { word: "Dissonance", def: "A lack of harmony; a clash between conflicting elements" },
        { word: "Primitive", def: "Belonging to the earliest stage of development; fundamental and ancient" },
      ],
    },
    rad: {
      label: "REGRESS",
      analysis:
        "Jekyll's final statement reveals the ultimate **regression**: his entire experiment, born of intellectual ambition and moral idealism, has produced only destruction. His 'recognition' comes too late — understanding duality theoretically does not prevent it from destroying him practically. This gap between knowledge and action is itself a form of regression: Jekyll ends knowing more but being less than when he started.",
      keyWords: [
        { word: "Intellectual ambition", def: "The desire to achieve great understanding or make important discoveries" },
        { word: "Knowledge-action gap", def: "The distance between understanding what is right and actually doing it" },
      ],
    },
    technique2: {
      title: "CONFESSIONAL MODE / EPISTOLARY STRUCTURE",
      analysis:
        "The final chapter shifts to **epistolary** (written as a letter or document) form: Jekyll's 'Full Statement' is a written confession read after his death. This structural choice is significant — Jekyll can only tell the truth in writing, not in person; and only posthumously, not while alive. The **confessional mode** (writing that reveals hidden truths about the self) requires the safety of death before full disclosure is possible.",
      secondPoint:
        "The epistolary structure also means the reader receives the truth without Jekyll's physical presence — we read his words but cannot see his face, ask questions, or judge his sincerity. This creates a final act of **concealment** even within confession: Jekyll controls the narrative from beyond the grave, shaping how we understand his story. The man who could not control his body maintains control of his **narrative**.",
      keyWords: [
        { word: "Epistolary", def: "Relating to letters; a narrative presented through written documents" },
        { word: "Confessional mode", def: "A literary form revealing hidden truths about the self" },
        { word: "Posthumous", def: "Occurring or published after death" },
      ],
    },
    context: {
      points: [
        {
          label: "THE CONFESSIONAL TRADITION",
          text: "The final chapter draws on the tradition of **Christian confession** — a formal acknowledgment of sin before God. But Jekyll's confession is addressed to Utterson, not to God; his seeking of understanding is **secular** (not religious) rather than spiritual. Stevenson suggests that in the modern world, the confessor is the lawyer, not the priest — institutional authority has replaced divine authority.",
        },
        {
          label: "VICTORIAN AUTOBIOGRAPHY",
          text: "The Victorian period produced extensive autobiographical writing focused on **moral self-examination** (systematic scrutiny of one's own character). Jekyll's statement parodies this tradition: he performs self-examination but uses it to explain, rather than repent, his crimes. Stevenson critiques a culture where the performance of introspection can substitute for genuine moral change.",
        },
      ],
      keyWords: [
        { word: "Secular", def: "Not connected with religious or spiritual matters" },
        { word: "Self-examination", def: "Systematic scrutiny of one's own character, motives, and behaviour" },
        { word: "Introspection", def: "The examination of one's own thoughts and feelings" },
      ],
    },
    wow: {
      title: "THE SHADOW (Jung)",
      analysis:
        "Carl Jung's concept of the **Shadow** describes the unconscious aspect of the personality that the conscious ego does not identify with — the dark, repressed, animalistic side of human nature. Hyde IS Jekyll's Shadow made flesh. Jung argued that the Shadow cannot be eliminated — only **integrated** (incorporated into conscious awareness). Jekyll's fatal error is attempting to separate rather than integrate his Shadow: he tries to exile evil from his personality rather than acknowledging it as part of himself. Jung would say that psychological health requires **confrontation** with the Shadow — accepting that darkness exists within oneself — not its chemical extraction. Stevenson's novella is a cautionary tale about the catastrophic consequences of refusing to integrate the dark aspects of identity: what you deny will eventually destroy you.",
      keyWords: [
        { word: "The Shadow", def: "Jung's concept of the repressed, dark side of the personality" },
        { word: "Integration", def: "Incorporating all aspects of the self into a unified, conscious whole" },
        { word: "Confrontation", def: "The act of facing something difficult or uncomfortable directly" },
      ],
    },
  },
];
